name: Run Insert Time Slots

on:
  schedule:
    - cron: '10 05 * * *'  # Runs at 10:40 AM IST (5:10 AM UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: ./SmartClassAutomation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Insert Time Slots script
        working-directory: ./SmartClassAutomation
        run: python your_script_name.py
