name: Run Insert Time Slots

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: ./SmartClassAutomation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode Firebase key
        run: |
          echo "${{ secrets.FIREBASE_SECRET }}" | base64 -d > ./SmartClassAutomation/firebase_key.json

      - name: Run Insert Time Slots script
        working-directory: ./SmartClassAutomation
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/SmartClassAutomation/firebase_key.json
        run: python insert_slot.prod.py
